### ISSUE TITLE
Trust Metric

### ISSUE THREAD

**Issue by atakanguney** [atakanguney/Semantic-Trustworthy-News#11]
We need to adopt a trust metric for news

**Comment by mericturan** [comment]
To build a trust metric, we should first decide the possible news features that we can make use of. I don't know if we can fetch all these data, but followings come to my mind at the first blush:

1. **publication date** of news to check freshness
2. **publication source** of news for credibility analysis
3. **number of comments** on the news
4. **number of shares** of the news
