### ISSUE TITLE
Meeting Time

### ISSUE THREAD

**Issue by mericturan** [atakanguney/Semantic-Trustworthy-News#33]
Dear Atakan and Esra,

I guess we need to meet couple of times as we did before the first progress presentation in order to finalize the project. I suggest you to do our next group meeting in December 19, Thursday. Since lectures will end in December 18, we can use the full day to study.

**Comment by esraonal** [comment]
I agree. I will be available

**Comment by mericturan** [comment]
Okey then, I sent you guys a calendar invitation for the whole day of December 19, starting at 10 am.
